FROM tiangolo/uvicorn-gunicorn:python3.11

WORKDIR /app

COPY ./server /app

# RUN apt-get update && apt-get install -y python3-venv
# RUN python -m venv ./venvRUN apt-get update && apt-get install -y python3-venv

# RUN chmod +x ./venv/bin/activate

RUN pip install --no-cache-dir --upgrade -r requirements.txt

CMD ["uvicorn", "server:app", "--proxy-headers", "--log-level", "debug", "--host", "0.0.0.0", "--port", "8001", "--reload"]