FROM python:3.9-slim

WORKDIR /app

COPY ./server /app

# Install the required packages inside the virtual environment
RUN pip install --no-cache-dir --upgrade -r requirements.txt
RUN pip install uvicorn

CMD ["uvicorn", "app:app","--proxy-headers", "--host", "0.0.0.0", "--port", "8000", "--reload"]