# Use an official Node.js runtime as the base image
FROM node:16

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY ./web/package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of your app's source code to the container
COPY ./web/ ./

# Build your Next.js app
RUN npm run build

# Expose the port your Next.js app listens on (usually 3000)
EXPOSE 3000

# Start your Next.js app
CMD ["npm", "start"]