version: '3'

services:
  fastapi_server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: fastapi_server
    volumes:
      - ./server:/app
    expose:
      - 8001
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  next_web:
    build:
      context: .
      dockerfile: Dockerfile.web
    volumes:
      - ./web:/app
      - /app/node_modules
      - /app/.next
    container_name: next_web
    expose:
      - 3000