version: '3'

services:
  server:
    image: python:3.9-slim
    container_name: server
    working_dir: /app
    volumes:
      - ./server:/app
    command: bash -c "pip install -r requirements.txt && python app.py"
    expose:
      - 5000

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - flask_app
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: web
    ports:
      - "3000:3000" 
