FROM nginx:alpine

COPY ./nginx/nginx.conf /etc/nginx/nginx.conf
COPY ./nginx/sites-available/ /etc/nginx/sites-available/

RUN mkdir -p /etc/nginx/sites-enabled

RUN ln -s /etc/nginx/sites-available/flask_site.conf /etc/nginx/sites-enabled/flask_site.conf
RUN ln -s /etc/nginx/sites-available/next.conf /etc/nginx/sites-enabled/next.conf

EXPOSE 80