version: '3'

services:
  fastapi_server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: fastapi_server
    volumes:
      - ./server:/app
    ports:
      - "8001:8001"
    expose:
      - 8001
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  discord_quart:
    build:
      context: ../shrillecho-discord
      dockerfile: Dockerfile.discord
    container_name: discord_quart
    volumes:
      - ../shrillecho-discord:/app
    expose:
      - 5000
  next_web:
    build:
      context: .
      dockerfile: Dockerfile.web
    volumes:
      - ./web:/app
      - /app/node_modules
      - /app/.next
    container_name: next_web
    expose:
      - 3000
  redis:
    image: "redis:latest"
    container_name: redis
    ports:
      - "6379:6379"